---
- name: Create a host group that only contains the host provided by vm_namespace and vm_name variables
  hosts: all
  gather_facts: no
  tasks:
    - name: Add host to group 'just_created'
      ansible.builtin.add_host:
        name: '{{ vm_namespace}}-{{ vm_name }}'
        groups: target_vm

- name: Install LAMP Stack on RHEL 9
  hosts: target_vm
  remote_user: "{{ vm_user }}"
  become: true
  vars: 
    vm_name: "{{ vm_namespace}}-{{ vm_name }}"

  tasks:
    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start and enable Apache
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: true

    - name: Install MariaDB
      ansible.builtin.dnf:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: true

    - name: Install PHP and common modules
      ansible.builtin.dnf:
        name:
          - php
          - php-mysqlnd
          - php-fpm
          - php-opcache
          - php-gd
          - php-xml
          - php-mbstring
        state: present

    - name: Restart Apache to load PHP modules
      ansible.builtin.systemd:
        name: httpd
        state: restarted

    - name: Expose http port with ClusterIP
      kubernetes.core.k8s_service:
        state: present
        name: "{{ vm_name }}-http"
        namespace: default
        ports:
        - port: 80
          protocol: TCP
        selector:
          kubevirt.io/domain: "{{ vm_name }}"

    - name: Expose the insecure service externally with a route
      redhat.openshift.openshift_route:
        service: "{{ vm_name }}-http"
        namespace: "{{ vm_namespace}}"
        termination: edge
        insecure_policy: redirect
